config/routes.rb
Rails.application.routes.draw do
  resources :bands
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy, :index]
  resources :sessions, only: [:new, :create, :destroy]

  root "application#welcome", as: "home"
  get "/sessions", to: "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  belongs_to :manager, class_name: "User", foreign_key: "manager_id"
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :description
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bands, class_name: 'Band', foreign_key: "manager_id", primary_key: 'id'

  validates_presence_of :name
  validates_presence_of :password_digest
  validates_presence_of :username
  validates_uniqueness_of :username

  has_secure_password

  def admin?
    self.role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_logged_in_user

  def welcome
  end

  def login(user)
    reset_session
    session[:user_id] = user.id
  end

  def add_error_message(message)
    flash[:errors] ||= []
    flash[:errors] << message
  end

  private

  def set_logged_in_user
    if !!session[:user_id] && User.exists?(session[:user_id])
      @logged_in_user = User.find(session[:user_id])
    else
      @logged_in_user = nil
    end
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_requested_band, only: [:show, :edit, :update, :destroy]

  def index
    @bands = Band.all
  end

  def new
    @requested_band = Band.new
  end

  def create
    @new_band = Band.create(band_params)
  end

  def show
    @members = @requested_band.members
  end

  private

  def set_requested_band
    @requested_band = Band.find(params[:id])
  end

  def band_params
    params.require(:band).permit(:description, :manager)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if !!@user && @user.authenticate(params[:password])
      login(@user)
      redirect_to user_path(@user)
    elsif !!@user
      flash.now[:errors] ||= []
      flash.now[:errors] << "Wrong password."
      render :new
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << "Invalid username."
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to home_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_requested_user, only: [:show, :edit, :update, :destroy]
  before_action :require_auth, only: [:edit, :update, :destroy]

  def show
  end

  def edit
    @roles = ["user","admin"]
  end

  def new
    @requested_user = User.new
  end

  def index
    unless !!@logged_in_user
      reject_auth
    end
    @users = User.all
  end

  def create
    @new_user = User.create(user_params)
    if User.exists?(@new_user.id)
      login(@new_user)
      redirect_to user_path(@new_user)
    else
      flash.now[:errors] = @new_user.errors.full_messages
      render :new
    end
  end

  def update
    if @requested_user.update(user_params)
      redirect_to user_path(@requested_user)
    else
      flash.now[:errors] = @requested_user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @requested_user.destroy
    flash[:success] = "Destroyed"
    reset_session
    redirect_to home_path
  end

  private

  def set_requested_user
    if !!params[:id] && User.exists?(params[:id])
      @requested_user = User.find(params[:id])
    else
      add_error_message("Invalid User")
      redirect_to users_path
    end
  end

  def user_params
    if !!@logged_in_user && @logged_in_user.admin?
      params.require(:user).permit(:username, :name, :password, :role)
    else
      params.require(:user).permit(:username, :name, :password)
    end
  end

  def reject_auth
    add_error_message("Not Authorized!")
    redirect_to home_path
  end

  def require_auth
    unless @requested_user == @logged_in_user || @logged_in_user.admin?
      reject_auth
    end
  end

  def require_admin_auth
    unless @logged_in_user.admin?
      reject_auth
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/welcome.html.erb
<% if !!@logged_in_user %>
<p><%= link_to "Users", users_path %></p>
<p><!%= link_to "Bands", bands_path %></p>
<p><!2%= link_to "Venues", venues_path %></p>
<% end %>

app/views/bands/index.html.erb
<h1>Bands</h1>
<ul>
<% @bands.each do |band| %>
  <li>
    <p><%= link_to band.name, band_path(band) %></p>
    <p><%= band.description %></p>
  </li>
<% end %>
</ul>

app/views/bands/show.html.erb
<h1><%= @requested_band.name %></h1>
<h2>Members</h2>
<ul>
<% @members.each do |member| %>
  <li><p><%= link_to member.name, user_path(member) %></p></li>
<% end %>
</ul>

app/views/layouts/_errors.html.erb
<% if flash.now[:errors] %>
  <ul>
    <% flash.now[:errors].each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
<% elsif flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_logout.html.erb
<%= link_to @logged_in_user.name, user_path(@logged_in_user) %>
<%= form_with url: "/sessions/#{session.id}", method: "delete" do |f| %>
<%= f.submit "Logout" %>
<% end %>

app/views/layouts/_success.html.erb
<% if flash[:success] %>
  <ul>
    <li><%= flash[:success] %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Band Social</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav>
      <%= link_to "Home", home_path  %>
      <% if !@logged_in_user %>
        <%= link_to "Login", new_session_path  %>
        <%= link_to "Sign Up", new_user_path  %>
      <% else %>
        <%= render "./layouts/logout" %>
      <% end %>
    </nav>
    <%= render "./layouts/errors" %>
    <%= render "./layouts/success" %>
    <%= yield %>
  </body>
</html>

app/views/users/_edit_form.html.erb
<%= form_with model: @requested_user, local: true do |f| %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name, required: true, autofocus: true  %>
  <br>
  <%= f.label :username %>
  <br>
  <%= f.text_field :username, required: true %>
  <br>
  <% if !!@logged_in_user && @logged_in_user == @requested_user %>
    <%= f.label :password %>
    <br>
    <%= f.password_field :password, required: true %>
    <br>
  <% end %>
  <% if !!@logged_in_user && @logged_in_user != @requested_user && @logged_in_user.admin? %>
    <%= f.label :role %>
    <%= f.collection_select :role, @roles, :to_s, :to_s %>
    <br>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/users/_new_form.html.erb
<%= form_with model: @requested_user, local: true do |f| %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name, required: true, autofocus: true  %>
  <br>
  <%= f.label :username %>
  <br>
  <%= f.text_field :username, required: true %>
  <br>
  <%= f.label :password %>
  <br>
  <%= f.password_field :password, required: true %>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1><%= "Edit #{@requested_user.name}" %></h1>
<%= render "edit_form" %>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "new_form" %>

app/views/users/show.html.erb
<h1><%= @requested_user.name %></h1>
<h2>@<%= @requested_user.username %></h2>
<h2>Role: <%= @requested_user.role %></h2>
<% if @requested_user == @logged_in_user || @logged_in_user.admin? %>
  <p><%= link_to "Edit Profile", edit_user_path %></p>
  <%= form_with url: user_path(@requested_user), method: "delete", local: true do |f| %>
    <%= f.submit "Delete Account"%>
  <% end %>
<% end %>